# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install FLask
        pip install selenium
        pip install fullmoon
        pip install requests
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with unittest
      run: python3 -u -m unittest tests.py
      
    - name: Run tests and coverage report
      run: | 
        coverage run --data-file tests/.coverage -m pytest -s
        coverage json --data-file tests/.coverage -o buf/tests/coverage.json
        coverage report --data-file tests/.coverage
      
      
      
      
        
