# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application
env: 
        HOLIDAY_API: ${{secrets.HOLIDAY_API}}
        FLASK: ${{secrets.FLASK}}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        echo ${{secrets.HOLIDAY_API}}
        python -m pip install --upgrade pip
        pip install FLask
        pip install selenium
        pip install fullmoon
        pip install requests
        pip install python-dotenv
      
        
    - name: Test with unittest
      run: python3 -u -m unittest tests.py
      

      
    
        
